{
 "title": "AdGuard Home",
 "description": "This is a AdGuard Home dashboard when using the https://github.com/henrywhitaker3/adguard-exporter Prometheus exporter",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "server",
    "query": "label_values(adguard_running,server)"
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Status",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "adguard_running{server=\"$server\"}",
     "legendFormat": "{{ legend }}"
    }
   ]
  },
  {
   "title": "Processing Time",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(adguard_processing_time_milliseconds_sum{server=\"$server\"}[$__rate_interval])) / sum(rate(adguard_processing_time_milliseconds_count{server=\"$server\"}[$__rate_interval]))"
    }
   ]
  },
  {
   "title": "Total Requests",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "adguard_queries", "legendFormat": "Total Requests" }
   ]
  },
  {
   "title": "Blocked Requests",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "adguard_queries_blocked", "legendFormat": "Blocked Requests" }
   ]
  },
  {
   "title": "% Blocked",
   "type": "stat",
   "gridPos": { "h": 4, "w": 7, "x": 17, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "(adguard_queries_blocked{server=\"$server\"}/ adguard_queries{server=\"$server\"}) * 100"
    }
   ]
  },
  {
   "title": "Client Queries",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "reqpm" } },
   "targets": [
    {
     "expr": "avg_over_time((adguard_top_clients - adguard_top_clients offset 1m)[5m:])",
     "legendFormat": "{{client}}"
    }
   ]
  },
  {
   "title": "Queries Blocked/Replaced",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "avg_over_time((adguard_queries_blocked - adguard_queries_blocked offset 1m)[5m:])",
     "legendFormat": "Blocked"
    },
    {
     "expr": "avg_over_time((adguard_queries - adguard_queries offset 1m)[5m:])",
     "legendFormat": "All Queries"
    }
   ]
  },
  {
   "title": "Top Queries by Domain",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(10, increase(adguard_top_queried_domains{server=\"$server\"}[$__range]))",
     "legendFormat": "{{domain}}"
    }
   ]
  },
  {
   "title": "Top Blocked by Domain",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 9, "x": 9, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(10, increase(adguard_top_blocked_domains{server=\"$server\"}[$__range]))",
     "legendFormat": "{{domain}}"
    }
   ]
  },
  {
   "title": "Top Clients",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(10, increase(adguard_top_clients{server=\"$server\"}[$__range]))",
     "legendFormat": "{{client}}"
    }
   ]
  },
  {
   "title": "Upstream Response Time",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum by (upstream) (rate(adguard_processing_time_milliseconds_sum[5m])) / sum by (upstream) (rate(adguard_processing_time_milliseconds_count[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Query Types",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(adguard_query_types{server=\"$server\"}[$__range])",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Upstreams",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 22 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(15, sum by (upstream) (increase(adguard_top_upstreams{server=\"$server\"}[$__range])))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 } },
  {
   "title": "Clients",
   "type": "table",
   "gridPos": { "h": 6, "w": 7, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "topk(15, sum by (client) (increase(adguard_top_clients{server=\"$server\"}[$__range])))",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by (client) (rate(adguard_processing_time_milliseconds_sum[$__rate_interval]))  / sum by (client) (rate(adguard_processing_time_milliseconds_count[$__rate_interval]) > 0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Top Blocked Domains",
   "type": "table",
   "gridPos": { "h": 11, "w": 9, "x": 7, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "topk(15, sum by (domain) (increase(adguard_top_blocked_domains[$__range])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Top Queries",
   "type": "table",
   "gridPos": { "h": 11, "w": 8, "x": 16, "y": 32 },
   "targets": [
    {
     "expr": "topk(15, sum by (domain) (increase(adguard_top_queried_domains[$__range])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Upstreams",
   "type": "table",
   "gridPos": { "h": 5, "w": 7, "x": 0, "y": 38 },
   "targets": [
    {
     "expr": "topk(15, sum by (upstream) (increase(adguard_top_upstreams{server=\"$server\"}[$__range])))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}