{
 "title": "Amazfit Dashboard",
 "time": { "from": "now-20d", "to": "now" },
 "panels": [
  {
   "title": "Resting HR",
   "type": "timeseries",
   "description": "Resting HR",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "Amazfit Resting HR",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "heartrate",
     "query": "SELECT min(\"value\") + 12 FROM \"heartrate\" WHERE $timeFilter GROUP BY time(1d) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "min"
       }
      ]
     ]
    },
    {
     "alias": "Fitbit RHR",
     "query": "SELECT distinct(\"value\") FROM \"restingHeartRate\" WHERE $timeFilter GROUP BY time($__interval) fill(null)"
    }
   ]
  },
  {
   "title": "Heart Rate",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Heart rate",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "heartrate",
     "query": "SELECT moving_average(mean(\"value\"), 6) FROM \"heartrate\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "6" ], "type": "moving_average" }
      ]
     ]
    },
    {
     "alias": "Above 95",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "heartrate",
     "query": "select above from (SELECT moving_average(mean(\"value\"), 6) as above FROM \"heartrate\" WHERE $timeFilter GROUP BY time($__interval) fill(null)) where above > 95",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "8" ], "type": "moving_average" }
      ]
     ],
     "tags": [
      { "key": "value", "operator": "=~", "value": "/^$RHR$/" }
     ]
    },
    {
     "alias": "Below RHR",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "heartrate",
     "query": "select below from (SELECT moving_average(mean(\"value\"), 6) as below FROM \"heartrate\" WHERE $timeFilter GROUP BY time($__interval) fill(null)) where below < 60",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "8" ], "type": "moving_average" }
      ]
     ],
     "tags": [
      { "key": "value", "operator": "=~", "value": "/^$RHR$/" }
     ]
    },
    {
     "alias": "Heart rate",
     "query": "SELECT moving_average(mean(\"value\"), 6) FROM \"heartrate\" WHERE $timeFilter GROUP BY time($__interval) fill(null)"
    },
    {
     "alias": "Above 95",
     "query": "select above from (SELECT moving_average(mean(\"value\"), 6) as above FROM \"heartrate\" WHERE $timeFilter GROUP BY time($__interval) fill(null)) where above > 95"
    },
    {
     "alias": "Below RHR",
     "query": "select below from (SELECT moving_average(mean(\"value\"), 6) as below FROM \"heartrate\" WHERE $timeFilter GROUP BY time($__interval) fill(null)) where below < 60"
    }
   ]
  },
  {
   "title": "Heart Rate",
   "type": "natel-discrete-panel",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 18 },
   "targets": [
    {
     "alias": "Heart rate",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "heartrate",
     "query": "SELECT mean(\"value\") FROM \"heartrate\" WHERE $timeFilter GROUP BY time(5m) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "6" ], "type": "moving_average" }
      ]
     ]
    },
    {
     "alias": "Heart rate",
     "query": "SELECT mean(\"value\") FROM \"heartrate\" WHERE $timeFilter GROUP BY time(5m) fill(null)"
    }
   ]
  },
  {
   "title": "Band wearing ",
   "type": "natel-discrete-panel",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 22 },
   "targets": [
    {
     "alias": "Amazfit",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "heartrate",
     "query": "SELECT mean(value) FROM \"heartrate\" WHERE $timeFilter GROUP BY time(10m) fill(0)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "6" ], "type": "moving_average" }
      ]
     ]
    },
    {
     "alias": "Fitbit",
     "query": "SELECT mean(value) FROM \"heartrate\" WHERE time < '2023-03-05 00:00:00' GROUP BY time(2m) fill(0)"
    }
   ]
  },
  {
   "title": "Sleep Pattern",
   "type": "natel-discrete-panel",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 26 },
   "targets": [
    {
     "alias": "Sleep levels",
     "groupBy": [
      { "params": [ "1h" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "sleep_periods",
     "query": "SELECT last(\"state\") FROM \"sleep_periods\" WHERE $timeFilter GROUP BY time(10m) fill(previous)",
     "select": [
      [
       { "params": [ "state" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    },
    {
     "alias": "All sleeps",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT last(sleep_type) FROM sleep_levels WHERE short = false GROUP BY time(10m) fill(previous)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Given duration Steps",
   "type": "gauge",
   "gridPos": { "h": 10, "w": 4, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "activity",
     "select": [
      [
       { "params": [ "steps" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    },
    {
     "query": "SELECT distinct(\"value\") FROM \"steps\" WHERE $timeFilter GROUP BY time($__interval) fill(null)"
    }
   ]
  },
  {
   "title": "Hourly walk heatmap",
   "type": "marcusolsson-hourly-heatmap-panel",
   "gridPos": { "h": 10, "w": 11, "x": 4, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "Hourly walk heatmap",
     "groupBy": [
      { "params": [ "1h" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "activity",
     "select": [
      [
       { "params": [ "steps" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    },
    {
     "query": "SELECT distinct(\"value\") FROM \"hourly_steps\" WHERE $timeFilter GROUP BY time($__interval) fill(null)"
    }
   ]
  },
  {
   "title": "Sleep Regularity",
   "type": "marcusolsson-hourly-heatmap-panel",
   "gridPos": { "h": 10, "w": 9, "x": 15, "y": 32 },
   "targets": [
    {
     "alias": "Hourly walk heatmap",
     "groupBy": [
      { "params": [ "30m" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "sleep_periods",
     "query": "SELECT last(\"state\") FROM \"sleep_periods\" WHERE $timeFilter AND time > '2023-03-05 00:00:00' GROUP BY time(1h) fill(previous)",
     "select": [
      [
       { "params": [ "state" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    },
    {
     "query": "SELECT mean(\"seconds\") FROM \"sleep_levels\" WHERE $timeFilter GROUP BY time(1h) fill(null)"
    }
   ]
  },
  {
   "title": "steps per minute",
   "type": "graph",
   "gridPos": { "h": 7, "w": 14, "x": 0, "y": 42 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Amazfit hourly steps",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "activity",
     "select": [
      [
       { "params": [ "steps" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    },
    {
     "alias": "Fitbit hourly steps",
     "query": "SELECT sum(\"value\") FROM \"hourly_steps\" WHERE $timeFilter GROUP BY time($__interval) fill(null)"
    }
   ]
  },
  {
   "title": "Sleep",
   "type": "graph",
   "gridPos": { "h": 15, "w": 10, "x": 14, "y": 42 },
   "yaxes": [
    { "format": "m" }
   ],
   "targets": [
    {
     "alias": "Deep",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "sleep",
     "query": "SELECT distinct(\"minutes_deep\") FROM \"sleep\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "minutes_deep" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "is_main_sleep", "operator": "=", "value": "true" }
     ]
    },
    {
     "alias": "Light",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "sleep",
     "query": "SELECT distinct(\"minutes_light\") FROM \"sleep\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "minutes_light" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "is_main_sleep", "operator": "=", "value": "true" }
     ]
    },
    {
     "alias": "REM",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "sleep",
     "query": "SELECT distinct(\"minutes_rem\") FROM \"sleep\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "minutes_light" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "is_main_sleep", "operator": "=", "value": "true" }
     ]
    },
    {
     "alias": "Awake",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "sleep",
     "query": "SELECT distinct(\"minutes_awake\") FROM \"sleep\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "minutes_light" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "is_main_sleep", "operator": "=", "value": "true" }
     ]
    },
    {
     "alias": "Deep",
     "query": "SELECT distinct(\"minutes_deep\") FROM \"sleep\" WHERE is_main_sleep = true AND $timeFilter GROUP BY time($__interval) fill(null)"
    },
    {
     "alias": "Light",
     "query": "SELECT distinct(\"minutes_light\") FROM \"sleep\" WHERE is_main_sleep = true AND $timeFilter GROUP BY time($__interval) fill(null)"
    },
    {
     "alias": "REM",
     "query": "SELECT distinct(\"minutes_rem\") FROM \"sleep\" WHERE is_main_sleep = true AND $timeFilter GROUP BY time($__interval) fill(null)"
    },
    {
     "alias": "Awake",
     "query": "SELECT distinct(\"minutes_awake\") FROM \"sleep\" WHERE is_main_sleep = true AND $timeFilter GROUP BY time($__interval) fill(null)"
    }
   ]
  },
  {
   "title": "Steps",
   "type": "graph",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 49 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Steps Amazfit",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "steps",
     "query": "SELECT sum(\"steps\") FROM \"activity\" WHERE $timeFilter GROUP BY time(1d) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ]
    },
    {
     "alias": "Steps Fitbit",
     "query": "SELECT distinct(\"value\") FROM \"steps\" WHERE $timeFilter GROUP BY time($__interval) fill(null)"
    }
   ]
  },
  {
   "title": "Distance",
   "type": "graph",
   "gridPos": { "h": 8, "w": 7, "x": 7, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "lengthm" } },
   "yaxes": [
    { "format": "lengthm" }
   ],
   "targets": [
    {
     "alias": "Distance Amazfit",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "steps",
     "query": "SELECT sum(\"steps\")*0.7 FROM \"activity\" WHERE $timeFilter GROUP BY time(1d) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ]
    },
    {
     "alias": "Distance Fitbit",
     "query": "SELECT distinct(\"value\") *1609.34 FROM \"distance\" WHERE $timeFilter GROUP BY time($__interval) fill(null)"
    }
   ]
  },
  {
   "title": "Hourly steps > 250",
   "type": "natel-discrete-panel",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 57 },
   "targets": [
    {
     "alias": "Amazfit",
     "groupBy": [
      { "params": [ "1h" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "activity",
     "select": [
      [
       { "params": [ "steps" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    },
    {
     "alias": "Fitbit",
     "groupBy": [
      { "params": [ "1h" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "hourly_steps",
     "query": "SELECT distinct(\"greater than 250\") FROM \"hourly_steps_sum\" WHERE time < '2023-03-05 00:00:00' GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    }
   ]
  }
 ]
}